import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header/Header'
import Intro from '@/components/Intro/Intro'
import Front from '@/components/Front/Front'
import About from '@/components/About/About'
import Skills from '@/components/Skills/Skills'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const title = ` Adwaith's personal website `
  return (
    <div className={styles.container}>
       <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Front > */}
      <Header />
      <Intro />
      {/* </Front> */}
      <About />
      <Skills />
    </div>
  )
}
